backend:
  name: git-gateway
  branch: master
  open_authoring: true

media_folder: src/images/featured/cards
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: 'content'
    label: 'Site Content'
    files:
      - label: 'links.yaml'
        name: 'links'
        file: 'src/data/links.yaml'
        fields:
          - label: Links
            name: links
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Url', name: 'url', widget: 'string' }
              - { label: 'Categories', name: 'categories', widget: 'list' }
              - { label: 'Tags', name: 'tags', widget: 'list' }
              - {
                  label: 'Image',
                  name: 'image',
                  widget: 'image',
                  required: false,
                }
              - {
                  label: 'Description',
                  name: 'description',
                  widget: 'markdown',
                }
